version: 2.1


executors:
  node:
    docker:
      - image: circleci/node:10-browsers

  rust:
    docker:
      - image: oasislabs/rust:latest
    environment:
      PATH: /root/.local/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-2019-08-26-x86_64-unknown-linux-gnu/lib
    resource_class: xlarge


commands:
  install_oasis:
    steps:
      - run:
          name: Install Tools
          command: |
            apt-get -qq update
            apt-get -qq install python curl git gcc
            curl --proto '=https' --tlsv1.2 -sSL https://get.oasis.dev | python - --toolchain unstable
            npm install -g lerna
            npm install -g yarn


jobs:
  build:
    executor: node

    steps:
      - checkout
      - run: |
          yarn
          yarn lint
          yarn build
          yarn test
          yarn coverage
      - run:
          # create an output directory with all the artifacts
          # generated by the build
          rm -rf output; mkdir -p output; for package in $(ls packages); do mkdir output/$package; cp -r  packages/$package/dist/* output/$package/; done

      - store_artifacts:
          path: output
      - persist_to_workspace:
          root: .
          paths:
            - output

  # Note that the test-e2e job uses a different executor because it requires
  # the ability to build the oasis toolchain, while the build job requires
  # the ability to run browser based tests.
  test-e2e:
    executor: rust
    steps:
      - checkout
      - install_oasis
      - run: yarn && yarn build
      - run: pushd packages/client/test/e2e && oasis build && popd
      - run: oasis-chain > /tmp/oasis-chain.log & yarn test:e2e

  deploy-staging:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          # CircleCI's AWS Credentials are allowed to assume a role that has S3
          # access in the staging account.
          name: Create an ~/.aws/config file to assume the staging role for aws.
          command: mkdir -p ~/.aws && printf "[profile staging]\nrole_arn = ${AWS_STAGING_ROLE_ARN}\ncredential_source = Environment\n" > ~/.aws/config
      - attach_workspace:
          at: oasis-client
      - run:
          name: Deploy to S3
          command: aws s3 sync --profile staging oasis-client/output/ s3://web3cjs-staging/oasis-client-latest/ --delete

  deploy-release:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          # CircleCI's AWS Credentials are allowed to assume a role that has S3
          # access in the staging account.
          name: Create an ~/.aws/config file to assume the staging role for aws.
          command: mkdir -p ~/.aws && printf "[profile staging]\nrole_arn = ${AWS_STAGING_ROLE_ARN}\ncredential_source = Environment\n" > ~/.aws/config
      - attach_workspace:
          at: oasis-client
      - run:
          name: Deploy to S3
          command: aws s3 sync --profile staging oasis-client/output/ s3://web3cjs-staging/oasis-client/ --delete


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test-e2e
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^@oasislabs*/
